### ISSUE TITLE
button corner radius is not working in iOS 10

### ISSUE THREAD

**Issue by rahulvyas** [carsonperrotti/CNPPopupController#65]
Is there any way to fix the corner radius issue in iOS 10.
I'm using iPhone 5S and iOS 10.1

I have tried 
1. button.layer.clipToBounds = true;
2. button.maskToBounds = true;

Both not working.

Can you check in iOS 10.1

**Comment by carsonperrotti** [comment]
I am not seeing that on iOS 10. Perhaps something is setting the appearance proxy in your code?

Here is an example with the radius set to 10px on iOS 10.
<img width="272" alt="screen shot 2016-10-14 at 9 07 54 am" src="https://cloud.githubusercontent.com/assets/2063102/19388468/ca35a1ec-91ed-11e6-9065-ccb1e5f7fc39.png">

**Comment by carsonperrotti** [comment]
@rahulvyas Can you please update the issues you open with a resolution? It would be good to know if the issue you opened was a problem in your code or a bug in mine.

**Comment by rahulvyas** [comment]
I haven't tested it again. I'll test and will update here.

**Comment by rahulvyas** [comment]
I have appearance proxy but how Do I disable it for CNPPopupController?

**Comment by carsonperrotti** [comment]
I'm going to close this issue, since it is not an issue with the library and this is not a place for general questions. 

I am going to give you one link to point you in the right direction, but I would suggest searching stack overflow or google for those kinds of questions. They are great resources.

[Start here](http://stackoverflow.com/questions/24136874/appearancewhencontainedin-in-swift)
