### ISSUE TITLE
Version 1.0 coming, give me your feedback

### ISSUE THREAD

**Issue by carsonperrotti** [carsonperrotti/CNPPopupController#83]
I am going to do a nice update and overhaul of CNPPopupController and finally push a 1.0 in the coming couple of weeks. If there's anything you want to see or suggestions you may have, take some time and leave a comment below.

**Comment by RojS** [comment]
Hi Carson, 
Excellent control, thanks. 

I made a quick and dirty hack in your code so that the delegate can supply the origin, end, and dismissed points so that I can use your control to display any view as a popup menu. It would be great if similar functionality was included “out of the box” in a future release. 


![simulator screen shot - iphone 6 - 2017-10-27 at 18 14 07](https://user-images.githubusercontent.com/25417839/32111449-376bef94-bb43-11e7-8fe4-68c1228c165b.png)

**Comment by ahamedsaifudeen** [comment]
Is new release still on track?
